name: Spring Boot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub 저장소 체크아웃
    - name: Check out code
      uses: actions/checkout@v3

    # 2. Java 설치
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: gradle # 또는 'maven'

    # 3. gradlew 파일에 실행 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # 4. 의존성 캐싱
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches # Maven 사용 시 변경 필요
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 5. 애플리케이션 빌드
    - name: Build with Gradle
      run: ./gradlew build # Maven 사용 시 `mvn package`로 변경

    # 6. 테스트 실행
    - name: Run tests
      run: ./gradlew test # Maven 사용 시 `mvn test`로 변경
